djangovue_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('games.urls'))
]

games/urls.py
from django.urls import path
from games.views import HomeView, MathGameView, AnagramGameView

app_name = 'games'
urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('math-game/', MathGameView.as_view(), name='math-game'),
    path('anagram-game/', AnagramGameView.as_view(), name='anagram-game')
  ]

games/models.py
from django.db import models

# Create your models here.

games/views.py
from django.views.generic import TemplateView

# Create your views here.
class HomeView(TemplateView):
  template_name = 'home.html'

class MathGameView(TemplateView):
  template_name = 'math-game.html'

class AnagramGameView(TemplateView):
  template_name = 'anagram-game.html'

templates/_base.html
<!DOCTYPE html>
{% block html %}
<html lang="en">
<head>
  {% block head %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="author" content="Pengyong Zhan">
  <meta name="email" content="zhan0789@algonquinlive.com">
  <title>{% block title %}{% endblock %} | Games</title>
  {% endblock %}
</head>
<body>
  {% block body %}
  <header>
    <nav>
      <a href="{% url 'games:homepage' %}">Home</a> |
      <a href="{% url 'games:math-game' %}">Math Game</a> |
      <a href="{% url 'games:anagram-game' %}">AnaGram Name</a>
    </nav>
  </header>
  {% block main %}{% endblock %}
  {% endblock %}
</body>
</html>
{% endblock %}

templates/_base_vue.html
{% extends '_base.html' %}

{% block html %}
<html lang="">
  <head>
  {% block head %}{{ block.super }}{%endblock%}
  <script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>
  <body>
  {% block body %}
    {{ block.super }}
    <noscript>
      <strong>We're sorry but vue_games doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  {% endblock body %}
  </body>
</html>
{% endblock html %}

templates/anagram-game.html
{% extends "_base_vue.html" %}

{% block title %}3{% endblock %}

{% block main %}
  <h1>3</h1>
{% endblock %}

templates/home.html
{% extends "_base.html" %}

{% block title %}1{% endblock %}

{% block main %}
  <h1>1</h1>
{% endblock %}

templates/math-game.html
{% extends "_base_vue.html" %}

{% block title %}2{% endblock %}

{% block main %}
  <h1>2</h1>
{% endblock %}